/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wpp_android_DatePickerDialog */

#ifndef _Included_wpp_android_DatePickerDialog
#define _Included_wpp_android_DatePickerDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wpp_android_DatePickerDialog
 * Method:    dateSelected
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_wpp_android_DatePickerDialog_dateSelected
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
